### PR TITLE
Make for MacOS

### PR DESCRIPTION
**Pull request by Larpoux**
**I modified the Makefile for building moonnuklear on MacOS.**

- I checked that the make/make install still works on a fresh Windows.
- checked that the make/make install still works on a fresh Linux.
- I modified (rapidly) the README to include the making on MacOS

I had to add a little patch in src/window.c, (function CreateWindow)  for MACOS (does not impact the 2 others making).

### CODE REVIEW

**Comment by stetre** [comment]
Thank you for your contribution.

**Comment by stetre** [comment]
I removed the need for passing the MACOS=1 flag to make. It should work but I have no means to test it (I haven't got any  apple). Let me know if it doesn't.

**Comment by Larpoux** [comment]
Congratulation ! :-)

Your Makefile runs fine on MacOS and Linux.

You are really better than me ;-)


Think to remove the first line (comment) of the Makefile, and correct 
the README.

Do you want I work on the html documentation ? My english is so bad that 
I cannot garantee a good job.



Le 13/05/2019 à 20:33, Stefano Trettel a écrit :

**Comment by stetre** [comment]
Nevermind, I'll do it (not that my english is much better, though... I'm Italian ;-)

I think I'll also remove the MacOS related stuff from the READMEs to the README in the moonlibs repository.

**Pull request merged**
